#install.packages("agricolae")
#install.packages("car")
data<-read.csv("S:/0Lab/statistics/0data.csv",header=T)
#data<-read.csv(file.choose(),header=T)
boxplot(value~trt, data=data)
analysis<-lm(value~as.factor(trt), data=data)
anova(analysis)
library(agricolae)
model<-aov(value~trt,data=data)
comparison<-duncan.test(model,"trt",main="value.dealt with different trt")
duncan.test(model,"trt",alpha=0.05,console=TRUE)
res <- LSD.test(model, 'trt', p.adj = 'bonferroni')
print(res$groups)

model = lm(value ~ VitD3OH + DHA + VitD3OH:DHA, data=data)
summary(model)
library(car)
Anova(model, type="II")
summary(model)
anova2 <- aov(value ~ VitD3OH + DHA + VitD3OH:DHA, data=data)
Anova(anova2, type="II")
TukeyHSD(anova2)
